services:
  grpc_server:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: lovco_grpc
    restart: unless-stopped
    ports:
      - "50051:50051"
    networks:
      - lovco_network
    depends_on:
      db:
        condition: service_healthy
    env_file:
      - .env
    environment:
      DB_HOST: ${DB_HOST:-db}
      DB_PORT: ${DB_PORT:-5432}
      DB_NAME: ${DB_NAME:-lovco}
      DB_USER: ${DB_USER}
      DB_PASSWORD: ${DB_PASSWORD}
    healthcheck:
      test: ["CMD", "/bin/grpc_health_probe", "-addr=localhost:50051"]
      interval: 30s
      timeout: 5s
      retries: 5
    
  db:
    image: postgres:18-alpine3.22
    container_name: lovco_postgres
    restart: always
    environment:
      POSTGRES_DB: ${DB_NAME:-lovco}
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - lovco-data:/var/lib/postgresql/data
      - ./server/scripts/01_create.sql:/docker-entrypoint-initdb.d/01_create.sql
    healthcheck:
      test: ["CMD", "pg_isready", "-U", "${DB_USER:-lovco}", "-d", "${DB_NAME:-lovco_db}"]
      interval: 10s
      timeout: 5s
      retries: 5
    networks:
      - lovco_network

volumes:
  lovco-data:

networks:
  lovco_network:
    driver: bridge
